### PR TITLE
Pass engine_args to create_engine in get_embedding_column_definition

### PR DESCRIPTION
**Pull request by michaelwnyc**
Pass engine_args to create_engine in get_embedding_column_definition.

Encountered this error when connecting to tidbcloud serverless cluster:

`sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'gateway01.eu-central-1.prod.aws.tidbcloud.com' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000))")`

### CODE REVIEW

**Comment by IANTHEREAL** [comment]
@michaelwnyc thanks for your contribution. Can you fix the lint ci issue?

**Comment by michaelwnyc** [comment]
@IANTHEREAL It should have been fixed

**Review by IANTHEREAL — APPROVED** [review]

**Comment by IANTHEREAL** [comment]
@michaelwnyc Thanks again

**Comment by michaelwnyc** [comment]
@IANTHEREAL Any chance to release a new version and also update llama-index-vector-stores-tidbvector's version list?

**Comment by IANTHEREAL** [comment]
@michaelwnyc we will release it ASAP in this week

**Comment by IANTHEREAL** [comment]
@michaelwnyc  We had released the update in tidb-vector 0.0.8. You can now update 'tidb-vector' in your environment.  Because the 'llama-index-vector-stores-tidbvector' requires 'tidb-vector' to be version '>=0.0.3,<1.0.0', it will also work

**Pull request merged**
